#!/usr/bin/env python3
"""Generate figures for ICML 2026 Position Paper on Carbon Footprint Reporting.

Only the figures actually included in carbon_position_paper.tex are produced:
  - carbon_by_model     (Figure 1)
  - regional_comparison (Figure 2)

Figure 3 (reporting_gap) is generated by generate_reporting_gap.py.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.size'] = 12
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
plt.rcParams['figure.dpi'] = 150

# UN SDG 13 "Climate Action" green for primary series (paper-wide brand color)
CLIMATE_GREEN = '#3F7E44'

# Sources: Strubell 2019 (BERT), Patterson 2021 (T5, Meena, GShard, GPT-3),
#          Meta 2022 (OPT-175B), Luccioni 2023 (BLOOM, Gopher), Meta 2023-2024 (Llama)
carbon_data = {
    'Model': ['BERT', 'GShard\n600B', 'BLOOM\n176B', 'T5', 'OPT\n175B', 'Meena',
              'Llama-2\n70B', 'Gopher\n280B', 'GPT-3\n175B', 'Llama-3.1\n405B'],
    'CO2_tons': [0.65, 4.3, 25, 47, 75, 96, 291, 380, 552, 8930],
    'Params_B': [0.3, 600, 176, 11, 175, 2.6, 70, 280, 175, 405]
}
df_carbon = pd.DataFrame(carbon_data)

fig, ax = plt.subplots(figsize=(7.5, 4.2))
bars = ax.bar(df_carbon['Model'], df_carbon['CO2_tons'], color=CLIMATE_GREEN)
ax.set_ylabel('Carbon Emissions (metric tons CO$_2$eq)')
ax.set_title('Training Carbon Footprint of Open-Source Models')
ax.set_yscale('log')
ax.set_ylim(0.1, 15000)

for bar, val in zip(bars, df_carbon['CO2_tons']):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() * 1.15,
            f'{val}', ha='center', va='bottom', fontsize=10)

plt.xticks(fontsize=11)
plt.tight_layout()
plt.savefig('figures/carbon_by_model.pdf', bbox_inches='tight', pad_inches=0.2)
plt.savefig('figures/carbon_by_model.png', bbox_inches='tight', pad_inches=0.2, dpi=300)
plt.close()
print("Saved: figures/carbon_by_model.{pdf,png}")

# Figure 2: Regional grid intensity comparison
regions = ['Quebec', 'France', 'UK', 'California', 'Germany', 'Japan', 'Poland', 'China', 'Australia']
intensity = [20, 60, 180, 210, 350, 450, 500, 530, 650]
gpu_hours = 1000
gpu_power_kw = 0.3
energy_kwh = gpu_hours * gpu_power_kw
co2_kg = [energy_kwh * i / 1000 for i in intensity]

fig, ax1 = plt.subplots(figsize=(7.5, 4.2))
x = np.arange(len(regions))
width = 0.6

bars = ax1.bar(x, intensity, width, color=CLIMATE_GREEN, alpha=0.8, label='Grid Intensity')
ax1.set_ylabel('Grid Carbon Intensity (gCO$_2$/kWh)', color=CLIMATE_GREEN)
ax1.set_xticks(x)
ax1.set_xticklabels(regions, rotation=45, ha='right')
ax1.tick_params(axis='y', labelcolor=CLIMATE_GREEN)

ax2 = ax1.twinx()
ax2.scatter(x, co2_kg, marker='D', color='#666666', s=25, zorder=5, label='CO$_2$ for 1000 GPU-hrs')
ax2.set_ylabel('CO$_2$ for 1000 GPU-hours (kg)', color='#666666')
ax2.tick_params(axis='y', labelcolor='#666666')

ax1.set_title('Regional Variation in Carbon Impact')
fig.tight_layout()
plt.savefig('figures/regional_comparison.pdf', bbox_inches='tight', pad_inches=0.3)
plt.savefig('figures/regional_comparison.png', bbox_inches='tight', pad_inches=0.3, dpi=300)
plt.close()
print("Saved: figures/regional_comparison.{pdf,png}")
